#!/bin/bash
set -e

psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE USER $WIKIJS_DB_USER PASSWORD '$WIKIJS_DB_PASS';"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE DATABASE $WIKIJS_DB_NAME WITH OWNER $WIKIJS_DB_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "REVOKE CONNECT ON DATABASE $WIKIJS_DB_NAME FROM PUBLIC;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CONNECT ON DATABASE $WIKIJS_DB_NAME TO $WIKIJS_DB_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CREATE ON DATABASE $WIKIJS_DB_NAME TO $WIKIJS_DB_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "ALTER ROLE $WIKIJS_DB_USER WITH CREATEROLE;"