#!/bin/bash
set -e

psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE USER $SONARQUBE_DB_USER PASSWORD '$SONARQUBE_DB_PASS';"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE DATABASE $SONARQUBE_DB_NAME WITH OWNER $SONARQUBE_DB_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "REVOKE CONNECT ON DATABASE $SONARQUBE_DB_NAME FROM PUBLIC;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CONNECT ON DATABASE $SONARQUBE_DB_NAME TO $SONARQUBE_DB_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CREATE ON DATABASE $SONARQUBE_DB_NAME TO $SONARQUBE_DB_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "ALTER ROLE $SONARQUBE_DB_USER WITH CREATEROLE;"