import requests
import os

BASE_URL = 'https://lidarr.cloudville.me'
HEADERS = {
    'X-Api-Key': os.environ.get('X_API_KEY')
}

movie_names = [
    '1920 - Evil Returns',
    '2 States',
    '3 Bachelors',
    '3 Idiots',
    '3G',
    '7 Khoon Maaf',
    'ABCD 2',
    'Aarakshan',
    'Aashiqui',
    'Aashiqui 2',
    'Aatma',
    'Aazaan',
    'Abhijeet Sawant Farida',
    'Action Jackson',
    'Action Replayy',
    'Agent Vinod',
    'Agneepath',
    'Aisha',
    'Ajab Gazabb Love',
    'Ajab Prem Ki Ghazab Kahani',
    'Aladin',
    'All Is Well',
    'All The Best',
    'Alone',
    'Always Kabhi Kabhi',
    'Ammaa Ki Boli',
    'Anjaana Anjaani',
    'Aurangzeb',
    'Baat Bann Gayi',
    'Bachna Ae Haseeno',
    'Badlapur',
    'Badmaash Company',
    'Badmashiyaan',
    'Bajatey Raho',
    'Bajrangi Bhaijaan',
    'Band Baaja Baraat',
    'Bang Bang',
    'Bangistan',
    'Barfi!',
    'Barkhaa',
    'Bbuddah Hoga Terra Baap',
    'Be-Careful',
    'Besharam',
    'Bewakoofiyaan',
    'Beyond Kismat',
    'Bhaag Johnny',
    'Bhaag Milkha Bhaag',
    'Bheja Fry 2',
    'Bhool Bhulaiyaa',
    'Bhoothnath Returns',
    'Billu',
    'Bin Bulaye Baraati',
    'Bittoo Boss',
    'Blood Money',
    'Blue',
    'Bobby Jasoos',
    'Bodyguard',
    'Bol Bachchan',
    'Bombay Velvet',
    'Boss',
    'Break Ke Baad',
    'Brothers',
    'Bullett Raja',
    'Bumboo',
    'Calender Girls',
    'Chaalis Chauraasi',
    'Chaar Din Ki Chandni',
    'Chakravyuh',
    'Chal Pichchur Banate Hain',
    'Chala Mussaddi Office Office',
    'Challo Driver',
    'Chance Pe Dance',
    'Chandni Chowk To China',
    'Chashme Baddoor',
    'Chatur Singh Two Star',
    'Chennai Express',
    'Chhodo Kal Ki Baatein',
    'Chillar Party',
    'Cigarette Ki Tarah',
    'CityLights',
    'Cocktail',
    'Commando - A One Man Army',
    'Creature 3D',
    'D Day',
    'DJ Dance Remixes Vol.3',
    'Daawat E Ishq',
    'Dabangg',
    'Dabangg 2',
    'Dam999',
    'Damadamm',
    'Darr At The Mall',
    'De Dana Dan',
    'Dedh Ishqiya',
    'Delhi Belly',
    'Department',
    'Desi Boyz',
    'Desi Kalakaar (Yo Yo Honey Singh)',
    'Detective Byomkesh Bakshy',
    'Dhoom',
    'Dhoom 2',
    'Dhoom 3',
    'Dil Bole Hadippa',
    'Dil Dhadakne Do',
    'Diliwaali Zaalim Girlfriend',
    'Dirty Picture',
    'Dishkiyaoon',
    'Do Knot Disturb',
    'Don',
    'Don 2',
    'Dostana',
    'Double Dhamaal',
    'Dr Cabbie',
    'Dum Laga Ke Haisha',
    'Dum Maaro Dum',
    'Ek Deewana Tha',
    'Ek Main Aur Ek Tu',
    'Ek Paheli Leela',
    'Ek Tha Tiger',
    'Ek Thi Daayan',
    'Ek Villain',
    'Ekam (Son of Soil)',
    'English Vinglish',
    'Everybody On the Dance Floor',
    'F.A.L.T.U',
    'Finding Fanny',
    'Force',
    'From Sydney Wih Love',
    'Fugly',
    'Fukrey',
    'Gabbar Is Back',
    'Gali Gali Chor Hai',
    'Gang Of Ghosts',
    'Gangs of Wasseypur',
    'Ghost',
    'Go Goa Gone',
    'God Tussi Great Ho',
    'Golmaal',
    'Golmaal 3',
    'Golmaal Returns',
    'Goreyan Nu Daffa Karo',
    'Gori Tere Pyaar Mein',
    'Grand Masti',
    'Gunday',
    'Haiwaizaada',
    'Hamari Adhuri Kahani',
    'Hannah Montana',
    'Happy Ending',
    'Happy New Year',
    'Hasee Toh Phasee',
    'Hate Story',
    'Hate Story 2',
    'Haunted',
    'Heartless',
    'Hero',
    'Heroine',
    'Heropanti',
    'Hey Bro',
    'Heyy Babyy',
    'High School Musical 2',
    'Highway',
    'Himmatwala',
    'Holiday',
    'Housefull',
    'Housefull 2',
    'Hum Hai Raahi Car Ke',
    'Hum Tum Shabana',
    'Humpty Sharma Ki Dulhania',
    'Humshakals',
    'Hunterrr',
    'I',
    'I Am Kalam',
    'I Am Singh',
    'I Hate Luv Storys',
    'I Love New Year',
    'I Me Aur Main',
    'Ishaqzaade',
    'Ishkq In Paris',
    'Ishq Ke Parindey',
    'Ishqedarriyaan',
    'Issaq',
    'Jaana Pehchana',
    'Jaane Tu Ya Jaane Na',
    'Jab Tak Hai Jaan',
    'Jab We Met',
    'Jackpot',
    'Jai Ho',
    'Jannat',
    'Jannat 2',
    'Jeena Hai Toh Thok Daal',
    'Jinhe Mera Dil Luteya',
    'Jism 2',
    'Jo Dooba So Paar',
    'Jo Hum Chahein',
    'Jodi Breakers',
    'Joker',
    'Jolly LLB',
    'Judah Falak',
    'Jumbo',
    'K.K Best Of Me Compilation Vol.1',
    'K.K Best Of Me Compilation Vol.2',
    'K.K Best Of Me Compilation Vol.3',
    'K.K Best Of Me Compilation Vol.4',
    'Kaanchi',
    'Kahaani',
    'Kai Po Che',
    'Kambhakkt Ishq',
    'Kaminey',
    'Karle Pyaar Karle',
    'Karthik Calling Karthik',
    'Karz',
    'Karzzzz',
    'Katti Batti',
    'Khamoshiyan',
    'Khap',
    'Khiladi 786',
    'Khoobsurat',
    'Kick',
    'Kill Dil',
    'Kis Kisko Pyaar Karoon',
    'Kismat Konnection',
    'Kismet Love Paisa Dilli',
    'KnockOut',
    'Krazzy 4',
    'Krrish 3',
    'Kuch Kuch Locha Hai',
    'Kuku Mathur Ki Jhand Ho Gayi',
    'Kurbaan',
    'Kyaa Super Kool Hain Hum',
    'Ladies Vs Ricky Bahl',
    'Lanka',
    'Lekar Hum Deewana Dil',
    'Life Is Beautiful',
    'Life Mein Hungama Hai',
    'Life Partner',
    'London Dreams',
    'London Paris New York',
    'Loot',
    'Lootera',
    'Love Aaj Kal',
    'Love Breakups Zindagi',
    'Love Sex Aur Dhoka',
    'Love Story 2050',
    'Luck',
    'Luv Ka The End',
    'Luv Shuv Te Chicken Khurana',
    'Luv U Soniyo',
    'Luv U... Mr. Kalakaar',
    'Madras Cafe',
    'Maharajas',
    'Main Tera Hero',
    'Makkhi',
    'Mary Kom',
    'Mausam',
    'Maximum',
    'Memoirs R.D Burman CD3',
    'Mere Brother Ki Dulhan',
    'Mere Dad Ki Maruti',
    'Michael Jackson',
    'Mickey Virus',
    'Miley Na Miley Hum',
    'Mr Joe B Carwahlo',
    'Mr.X',
    'Mujhse Fraaandship Karoge',
    'Murder 2',
    'Murder 3',
    'My Name Is Khan',
    'NH10',
    'Nautanki Saala',
    'New York',
    'No Problem',
    'OMG Oh My God',
    'Once  Upon A Time In Mumbai',
    'Once Upon A Time In Mumbaai Dobara',
    'One By Two',
    'One Two Three',
    'PK',
    'Paathshaala',
    'Pappu Cant Dance Saala',
    'Partner',
    'Patiala House',
    'Phantom',
    'Phhir',
    'Piku',
    'Players',
    'Prince',
    'Purani Jeans',
    'Pyaar Impossible',
    'Qasam Se Qasam Se',
    'Queen',
    'Ra. One',
    'Raaz 3',
    'Raaz The Mystery Continues',
    'Rab Ne Bana Di Jodi',
    'Rabba Main Kya Karoon',
    'Race 2',
    'Radio',
    'Ragini MMS',
    'Ragini MMS 2',
    'Raja Natwarlal',
    'Rakhtbeej',
    'Ram Leela',
    'Ramaiya Vastavaiya',
    'Rang Rasiya',
    'Rangrezz',
    'Rascals',
    'Ready',
    'Revolver Rani',
    'Roadside Romeo',
    'Robot',
    'RockStar',
    'Rowdy Rathore',
    'Roy',
    'Rush',
    'Saare Jahaan Se Mehnga',
    'Sadda Adda',
    'Saheb Biwi Aur Gangster Returns',
    'Sahi Dhandhe Galat Bande',
    'Samrat & Co',
    'Satya 2',
    'Satyagraha',
    'Selected',
    'Shaadi Ke Side Effects',
    'Shaandaar',
    'Shaitaan',
    'Shakal Pe Mat Ja',
    'Shamitabh',
    'Shanghai',
    'Shaukeens',
    'Shirin Farhad Ki Toh Nikal Padi',
    'Shootout At Wadala',
    'Shortcut Romeo',
    'Shuddh Desi Romance',
    'Singh Is Kinng',
    'Singh Saab The Great',
    'Singh is Bliing',
    'Singham',
    'Singham Returns',
    'Son Of Sardaar',
    'Sonali Cable',
    'Sooper Se Ooper',
    'Soulful Voice K.K',
    'Soundtrack',
    'Spark',
    'Special 26',
    'Speedy Singh',
    'Stanley Ka Dabba',
    'Student Of The Year',
    'Super Nani',
    'Taare Zameen Par',
    'Table No. 21',
    'Talaash',
    'Tamanchey',
    'Tanu Weds Manu Returns',
    'Tanu weds Manu',
    'Tara Rum Pum',
    'Tees Maar Khan',
    'Tell Me O Kkhuda',
    'Tere Mere Phere',
    'Tere Naal Love Ho Gaya',
    'Teri Meri Kahaani',
    'Tevar',
    'Tezz',
    'Thank You',
    'The Real Life Of Mandi',
    'The Xpose',
    'Thoda Pyar Thoda Magic',
    'Total Siyapaa',
    'Tum Mile',
    'Tunak Tunak Tumba',
    'Tutiya Dil',
    'Unforgettable',
    'Ungli',
    'Vicky Donor',
    'Wake Up Sid',
    'Wanted',
    'War Chhod Na Yaar',
    'Wedding Pullav',
    'Welcome',
    'Welcome Back',
    'Welcome To Karachi',
    'Whats Your Raashee',
    'Will You Marry Me',
    'Yaar Anmulle',
    'Yaariyan',
    'Yamla Pagla Deewana',
    'Yamla Pagla Deewana 2',
    'Yarra O Dildaara',
    'Ye Stupid Pyar',
    'Yeh Jawaani Hai Deewani',
    'Yo Yo Hits (2013)',
    'Youngistaan',
    'Yuvvraj',
    'Zanjeer',
    'Zid',
    'Zindagi Na Milegi Dobara',
    'Zokkomon'
]

def find_movie(movie_name):
    # results = requests.get(BASE_URL + '/api/v3/movie/lookup?term={}'.format(movie_name), headers=HEADERS).json()
    results = requests.get(BASE_URL + '/api/v1/search?term={}'.format(movie_name), headers=HEADERS).json()
    if len(results) <= 0:
        return
    return results[0]

def add_movie(movie):
    movie = lidarr_payload(movie)
    sc = requests.post(BASE_URL + '/api/v1/album', json=movie, headers=HEADERS).status_code
    print ('INFO: Status Code = {}'.format(sc))
    if sc == 409:
        print("INFO: Already added movie: {}".format(movie['album']['title']))
    return sc == 201

def lidarr_payload(movie):
    payload = movie.copy()
    payload.update(payload['album'])
    payload['artist']['addOptions'] = {
        "monitor": "all",
        "searchForMissingAlbums": False
    }
    payload["addOptions"] = {
        "searchForNewAlbum": False
    }
    payload['artist']["qualityProfileId"] = 1
    payload["monitored"] = True
    payload["minimumAvailability"] = "announced"
    payload['artist']["rootFolderPath"] = "/music/"

    del payload['album']
    del payload['id']

    return payload


def create_movie_record(movie_name):
    movie = find_movie(movie_name)
    if movie is None:
        print("INFO: No results found for movie: '{}'.".format(movie_name))
        return
    added = add_movie(movie)
    if not added:
        print ('ERROR: Failed to add the movie: "{}"'.format(movie['album']['title']))
        return
    print ("Movie added successfully: '{}'".format(movie_name))
    return movie['album']['title']



def import_movie(movie_name, official_movie_name):
    file_path = '/downloads/completed/Media/Movies/Bollywood/{}'.format(movie_name)


def import_all():
    for movie_name in movie_names:
        try:
            official_movie_name = create_movie_record(movie_name)
        except:
            print("Some uncaught error occurred while adding: {}".format(movie_name))

if __name__ == '__main__':
    import_all()
