#!/bin/bash
set -e

psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE USER $PERSONAL_DB_USER PASSWORD '$PERSONAL_DB_PASS';"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE DATABASE $PERSONAL_DB_NAME WITH OWNER $PERSONAL_DB_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT ALL PRIVILEGES ON DATABASE $PERSONAL_DB_NAME TO $PERSONAL_DB_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "ALTER ROLE $PERSONAL_DB_USER WITH CREATEROLE;"
