#!/bin/bash
set -e

psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE USER $FRESHRSS_DB_USER PASSWORD '$FRESHRSS_DB_PASS';"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE DATABASE $FRESHRSS_DB_NAME WITH OWNER $FRESHRSS_DB_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT ALL PRIVILEGES ON DATABASE $FRESHRSS_DB_NAME TO $FRESHRSS_DB_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "ALTER ROLE $FRESHRSS_DB_USER WITH CREATEROLE;"
