#!/bin/bash
set -e

psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE USER $POSTIZ_USER PASSWORD '$POSTIZ_PASSWORD';"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE DATABASE $POSTIZ_DB WITH OWNER $POSTIZ_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "REVOKE CONNECT ON DATABASE $POSTIZ_DB FROM PUBLIC;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CONNECT ON DATABASE $POSTIZ_DB TO $POSTIZ_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CREATE ON DATABASE $POSTIZ_DB TO $POSTIZ_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "ALTER ROLE $POSTIZ_USER WITH CREATEROLE;"
