services:
  metabase:
    image: metabase/metabase:v0.58.24
    container_name: metabase
    restart: unless-stopped
    environment:
      TZ: ${HOST_TZ}
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_PG_DATABASE}
      MB_DB_PORT: 5432
      MB_DB_USER: ${MB_PG_USER}
      MB_DB_PASS: ${MB_PG_PASSWORD}
      MB_DB_HOST: postgres
      MB_JETTY_PORT: 3000
    ports:
      - ${METABASE_WEB_PORT}:3000
    volumes:
      - ${METABASE_MOUNT_DIR}:/metabase.db
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s

  postgres:
    image: postgres:16.8-alpine3.21
    container_name: metabase_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${MB_PG_USER}
      POSTGRES_PASSWORD: ${MB_PG_PASSWORD}
      POSTGRES_DB: ${MB_PG_DATABASE}
    volumes:
      - ${MB_PG_MOUNT_DIR}:/var/lib/postgresql/data
