host_user: mrishab
host_app_dir: /var/server/anton
host_data_dir: /mnt/external_hdd
enabled_apps:
  - affine
  - bentopdf
  - cadvisor
  - cloudflared
  - codeserver
  - ddns
  - deluge
  - dockovpn
  - duplicati
  - ghost
  - grafana
  - hermes
  - homarr
  - immich
  - jenkins
  - jupyter
  - mediaserver
  - nextcloud
  - ollama
  - ombi
  - open-webui
  - plex
  - prowlarr
  - reverse-proxy
  - sftpgo
  - sonarqube
  - stirling-pdf
  - tautulli
  - upsnap
