enabled_apps:
  - adguardhome
  - affine
  - airflow
  - bentopdf
  - calibre
  - codeserver
  - deluge
  - dockovpn
  - duplicati
  - epg
  - freshrss
  - ghost
  - immich
  - jellyfin
  - jenkins
  - jupyter
  - lazylibrarian
  - mediaserver
  - n8n
  - nextcloud
  - nexus
  - nzbget
  - ollama
  - ombi
  - open-webui
  - pgadmin
  - plex
  - postiz
  - prowlarr
  - registry
  - sftpgo
  - sonarqube
  - stirling-pdf
  - tautulli
  - threadfin
  - upsnap
  - wikijs
