host_user: mrishab
rsync_path: "sudo rsync"
host_app_dir: /var/server/anton
host_data_dir: /mnt/external_hdd
enabled_apps:
  - adguardhome
  - affine
  - airflow
  - bentopdf
  - cadvisor
  - calibre
  - cloudflared
  - codeserver
  - ddns
  - deluge
  - dockovpn
  - duplicati
  - elk
  - epg
  - freshrss
  - ghost
  - grafana
  - hermes
  - homarr
  - immich
  - jellyfin
  - jenkins
  - jupyter
  - lazylibrarian
  - lb
  - mediaserver
  - n8n
  - nextcloud
  - nexus
  - nzbget
  - ollama
  - ombi
  - open-webui
  - pgadmin
  - plex
  - postiz
  - prometheus
  - prowlarr
  - registry
  - reverse-proxy
  - sftpgo
  - sonarqube
  - stirling-pdf
  - tautulli
  - threadfin
  - upsnap
  - wikijs

blocked_env_sync_apps:
  - cloudflared
