host_user: mrishab
host_app_dir: /var/server/anton
host_data_dir: /mnt/external_hdd
enabled_apps:
  - affine
  - bentopdf
  - codeserver
  - deluge
  - dockovpn
  - duplicati
  - ghost
  - immich
  - jenkins
  - jupyter
  - nextcloud
  - ollama
  - ombi
  - open-webui
  - plex
  - prowlarr
  - sftpgo
  - sonarqube
  - stirling-pdf
  - tautulli
  - upsnap
