host_user: mrishab
host_app_dir: /var/server/anton
host_data_dir: /mnt/external_hdd
enabled_apps:
  - cadvisor
  - cloudflared
  - prometheus
  - sftpgo
  - wazuh

blocked_env_sync_apps:
  - cloudflared
