version: '3'

services:
  duplicati:
    container_name: duplicati
    image: ghcr.io/linuxserver/duplicati:latest
    restart: unless-stopped
    ports:
      - ${DUPLICATI_WEB_UI_PORT}:8200
    environment:
      PUID: ${APP_PUID}
      PGID: ${APP_PGID}
      TZ: ${HOST_TZ}
      SETTINGS_ENCRYPTION_KEY: ${DUPLICATI_SETTINGS_ENCRYPTION_KEY}
    volumes:
      - ${DUPLICATI_CONFIG_MOUNT_DIR}:/config
      - ${DUPLICATI_PRIMARY_BACKUPS_MOUNT_DIR}:/primary_backups
      - ${DUPLICATI_SECONDARY_BACKUPS_MOUNT_DIR}:/secondary_backups
      - ${DUPLICATI_SOURCE_MOUNT_DIR}:/source
