services:
    ddclient_cloudflare:
        image: ghcr.io/linuxserver/ddclient:4.0.0
        container_name: ddclient_cloudflare
        restart: unless-stopped
        environment:
            PUID: ${DDNS_PUID}
            PGID: ${DDNS_PGID}
            TZ: ${HOST_TZ}
        volumes:
            - ./static/config/cloudflare.conf:/config/ddclient.conf
