version: '3'

services:
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextcloud-mrishab:32.0-apache
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - ${NC_PORT}:80
    environment:
      # App Config
      NEXTCLOUD_ADMIN_USER: ${NC_ADMIN_USERNAME}
      NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NC_TRUSTED_DOMAINS}
      NEXTCLOUD_DEFAULT_PHONE_REGION: ${NC_DEFAULT_PHONE_REGION}
      # Reverse Proxy Config
      OVERWRITEPROTOCOL: https
      # Redis Config
      REDIS_HOST: redis
      REDIS_HOST_PORT: 6379
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${NC_MOUNT_DIR}:/var/www/html
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:9.6.22-alpine3.14
    container_name: nextcloud_postgres
    restart: unless-stopped
    environment:
      # PG Super User
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      # PG: Nextcloud
      NEXTCLOUD_DB: ${NC_DATABASE}
      NEXTCLOUD_USER: ${NC_USERNAME}
      NEXTCLOUD_PASSWORD: ${NC_PASSWORD}
    volumes:
      - ${PG_MOUNT_DIR}:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_MOUNT_DIR}:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
