#!/bin/bash
set -e

psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE USER $NEXTCLOUD_USER PASSWORD '$NEXTCLOUD_PASSWORD';"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE DATABASE $NEXTCLOUD_DB WITH OWNER $NEXTCLOUD_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "REVOKE CONNECT ON DATABASE $NEXTCLOUD_DB FROM PUBLIC;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CONNECT ON DATABASE $NEXTCLOUD_DB TO $NEXTCLOUD_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CREATE ON DATABASE $NEXTCLOUD_DB TO $NEXTCLOUD_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "ALTER ROLE $NEXTCLOUD_USER WITH CREATEROLE;"