primary_owner: mrishab

app_configs:
  adguardhome:
    port: [3000, 53]
    dirs:
      - { path: "{{ host_data_dir }}/adguard/work" }
      - { path: "{{ host_data_dir }}/adguard/conf" }
  affine:
    port: 3010
    dirs:
      - { path: "{{ host_data_dir }}/affine/db", mode: "0700" }
      - { path: "{{ host_data_dir }}/affine/app/uploads" }
      - { path: "{{ host_data_dir }}/affine/app/config" }
  airflow:
    port: 2364
    dirs:
      - {
          path: "{{ host_data_dir }}/airflow/app/plugins",
          owner: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/airflow/app/dags",
          owner: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/airflow/app/logs",
          owner: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/airflow/db",
          owner: "{{ primary_owner }}",
          mode: "0700",
        }
  bentopdf:
    port: 8085
    dirs:
      - {
          path: "{{ host_data_dir }}/bentopdf/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/bentopdf/data",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  calibre:
    port: [8080, 8081, 8083]
    dirs:
      - {
          path: "{{ host_data_dir }}/calibre/calibre-db/books",
          owner: "201",
          group: "201",
        }
      - {
          path: "{{ host_data_dir }}/calibre/calibre-web/config",
          owner: "201",
          group: "201",
        }
  codeserver:
    port: 2342
    dirs:
      - {
          path: "{{ host_data_dir }}/codeserver/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  deluge:
    port: 8112
    dirs:
      - {
          path: "{{ host_data_dir }}/mediaserver/downloads",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/deluge/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  dockovpn:
    port: 8386
    dirs:
      - {
          path: "{{ host_data_dir }}/dockovpn",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  duplicati:
    port: 8200
    dirs:
      - {
          path: "{{ host_data_dir }}/duplicati/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
          mode: "0700",
        }
  epg:
    port: 30000
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/epg/public" }
  freshrss:
    port: 4523
    dirs:
      - { path: "{{ host_data_dir }}/freshrss/app" }
      - { path: "{{ host_data_dir }}/freshrss/db", mode: "0700" }
  ghost:
    port: 2368
    dirs:
      - {
          path: "{{ host_data_dir }}/ghost/app",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/ghost/db",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  immich:
    port: 2283
    dirs:
      - { path: "{{ host_data_dir }}/immich/app/library" }
      - { path: "{{ host_data_dir }}/immich/db/postgres" }
      - { path: "{{ host_data_dir }}/immich/ml-cache" }
  jellyfin:
    port: 8096
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/jellyfin/config" }
      - { path: "{{ host_data_dir }}/mediaserver/jellyfin/cache" }
  jenkins:
    port: [8888, 50000]
    dirs:
      - {
          path: "{{ host_data_dir }}/jenkins",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  jupyter:
    port: 2705
    dirs:
      - {
          path: "{{ host_data_dir }}/jupyter/home/jovyan",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  lazylibrarian:
    port: 5299
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/lazylibrarian/config" }
  mediaserver:
    port: [8989, 7878, 8686, 6767]
    dirs:
      - {
          path: "{{ host_data_dir }}/mediaserver/downloads",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/music",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/movies",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/tv",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/courses",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/sonarr/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/radarr/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/lidarr/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/bazarr/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  n8n:
    port: 5678
    dirs:
      - { path: "{{ host_data_dir }}/n8n/app" }
      - { path: "{{ host_data_dir }}/n8n/db", mode: "0700" }
  nextcloud:
    port: 8765
    dirs:
      - {
          path: "{{ host_data_dir }}/nextcloud/db",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
          mode: "0700",
        }
      - {
          path: "{{ host_data_dir }}/nextcloud/html",
          owner: "www-data",
          group: "www-data",
        }
      - {
          path: "{{ host_data_dir }}/nextcloud/redis",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  nexus:
    port: 4634
    dirs:
      - {
          path: "{{ host_data_dir }}/nexus/nexus",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  nzbget:
    port: 6789
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/nzbget/config" }
  ollama:
    port: 11434
    dirs:
      - { path: "{{ host_data_dir }}/ollama" }
  ombi:
    port: 3579
    dirs:
      - { path: "{{ host_data_dir }}/ombi/config" }
  open-webui:
    port: 11435
    dirs:
      - { path: "{{ host_data_dir }}/open-webui" }
  pgadmin:
    port: 3487
    dirs:
      - {
          path: "{{ host_data_dir }}/pgadmin",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
          mode: "0750",
        }
      - {
          path: "{{ host_data_dir }}/postgresdb",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  plex:
    port: 32400
    dirs:
      - {
          path: "{{ host_data_dir }}/mediaserver/plex/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/plex/transcode",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/music",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/movies",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/tv",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/courses",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  postiz:
    port: 5000
    dirs:
      - {
          path: "{{ host_data_dir }}/postiz/app/config",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/postiz/app/uploads",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/postiz/db/data",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/postiz/redis/data",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  prowlarr:
    port: 9696
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/prowlarr/config" }
  registry:
    port: 5000
    dirs:
      - { path: "{{ host_data_dir }}/registry" }
  sftpgo:
    port: [9393, 2022, 2121]
    dirs:
      - {
          path: "{{ host_data_dir }}/sftpgo/srv/sftpgo",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/sftpgo/var/lib/sftpgo",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  sonarqube:
    port: 3124
    dirs:
      - {
          path: "{{ host_data_dir }}/sonarqube/db",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
          mode: "0700",
        }
      - {
          path: "{{ host_data_dir }}/sonarqube/app/data",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/sonarqube/app/extensions",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/sonarqube/app/logs",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  stirling-pdf:
    port: 8086
    dirs:
      - {
          path: "{{ host_data_dir }}/stirling-pdf/configs",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/stirling-pdf/logs",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/stirling-pdf/tessdata",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
      - {
          path: "{{ host_data_dir }}/stirling-pdf/pipeline",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  tautulli:
    port: 8181
    dirs:
      - { path: "{{ host_data_dir }}/tautulli/config" }
  threadfin:
    port: 34400
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/threadfin/config" }
      - { path: "{{ host_data_dir }}/mediaserver/threadfin/temp" }
  upsnap:
    port: 8090
    dirs:
      - {
          path: "{{ host_data_dir }}/upsnap/data",
          owner: "{{ primary_owner }}",
          group: "{{ primary_owner }}",
        }
  wikijs:
    port: 3123
    dirs:
      - { path: "{{ host_data_dir }}/wikijs/db", mode: "0700" }
