app_configs:
  adguardhome:
    port: [ 10007, 53 ]
    dirs:
      - { path: "{{ host_data_dir }}/adguardhome/adguard_work_mount_dir" }
      - { path: "{{ host_data_dir }}/adguardhome/adguard_conf_mount_dir" }
  affine:
    port: 3010
    dirs:
      - { path: "{{ host_data_dir }}/affine/db", mode: "0700" }
      - { path: "{{ host_data_dir }}/affine/app/uploads" }
      - { path: "{{ host_data_dir }}/affine/app/config" }
  airflow:
    port: 2364
    dirs:
      - { path: "{{ host_data_dir }}/airflow/app/plugins", owner: "1000" }
      - { path: "{{ host_data_dir }}/airflow/app/dags", owner: "1000" }
      - { path: "{{ host_data_dir }}/airflow/app/logs", owner: "1000" }
      - { path: "{{ host_data_dir }}/airflow/db", owner: "1000", mode: "0700" }
  bentopdf:
    port: 8085
    dirs:
      - { path: "{{ host_data_dir }}/bentopdf/config", owner: "1000", group: "1000" }
      - { path: "{{ host_data_dir }}/bentopdf/data", owner: "1000", group: "1000" }
  calibre:
    port: [ 8080, 8081, 8083 ]
    dirs:
      - {
          path: "{{ host_data_dir }}/calibre/calibre-db/books",
          owner: "201",
          group: "201",
        }
      - {
          path: "{{ host_data_dir }}/calibre/calibre-web/config",
          owner: "201",
          group: "201",
        }
  codeserver:
    port: 10011
    dirs:
      - {
          path: "{{ host_data_dir }}/codeserver/codeserver_mount_dir",
          owner: "1000",
          group: "1000",
        }
  deluge:
    port: 10004
    dirs:
      - {
          path: "{{ host_data_dir }}/deluge/downloads_mount_dir",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/deluge/deluge_config_mount_dir",
          owner: "1000",
          group: "1000",
        }
  dockovpn:
    port: 8386
    dirs:
      - { path: "{{ host_data_dir }}/dockovpn", owner: "1000", group: "1000" }
  duplicati:
    port: 8200
    dirs:
      - {
          path: "{{ host_data_dir }}/duplicati/config",
          owner: "1000",
          group: "1000",
          mode: "0700",
        }
  epg:
    port: 30000
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/epg/public" }
  freshrss:
    port: 4523
    dirs:
      - { path: "{{ host_data_dir }}/freshrss/app" }
      - { path: "{{ host_data_dir }}/freshrss/db", mode: "0700" }
  ghost:
    port: 2368
    dirs:
      - { path: "{{ host_data_dir }}/ghost/app", owner: "1000", group: "1000" }
      - { path: "{{ host_data_dir }}/ghost/db", owner: "1000", group: "1000" }
  immich:
    port: 2283
    dirs:
      - { path: "{{ host_data_dir }}/immich/app/library" }
      - { path: "{{ host_data_dir }}/immich/db/postgres" }
      - { path: "{{ host_data_dir }}/immich/ml-cache" }
  jellyfin:
    port: 8096
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/jellyfin/config" }
      - { path: "{{ host_data_dir }}/mediaserver/jellyfin/cache" }
  jenkins:
    port: [ 10021, 10022, 10023 ]
    dirs:
      - {
          path: "{{ host_data_dir }}/jenkins/jenkins_mount_dir",
          owner: "1000",
          group: "1000",
        }
  jupyter:
    port: 2705
    dirs:
      - {
          path: "{{ host_data_dir }}/jupyter/home/jovyan",
          owner: "1000",
          group: "1000",
        }
  lazylibrarian:
    port: 5299
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/lazylibrarian/config" }
  mediaserver:
    port: [ 8989, 7878, 8686, 6767 ]
    dirs:
      - {
          path: "{{ host_data_dir }}/mediaserver/downloads",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/music",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/movies",
          owner: "1000",
          group: "1000",
        }
      - { path: "{{ host_data_dir }}/mediaserver/tv", owner: "1000", group: "1000" }
      - {
          path: "{{ host_data_dir }}/mediaserver/courses",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/sonarr/config",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/radarr/config",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/lidarr/config",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/mediaserver/bazarr/config",
          owner: "1000",
          group: "1000",
        }
  n8n:
    port: 5678
    dirs:
      - { path: "{{ host_data_dir }}/n8n/app" }
      - { path: "{{ host_data_dir }}/n8n/db", mode: "0700" }
  nextcloud:
    port: 8765
    dirs:
      - {
          path: "{{ host_data_dir }}/nextcloud/db",
          owner: "1000",
          group: "1000",
          mode: "0700",
        }
      - {
          path: "{{ host_data_dir }}/nextcloud/html",
          owner: "www-data",
          group: "www-data",
        }
      - { path: "{{ host_data_dir }}/nextcloud/redis", owner: "1000", group: "1000" }
  nexus:
    port: 4634
    dirs:
      - { path: "{{ host_data_dir }}/nexus/nexus", owner: "1000", group: "1000" }
  nzbget:
    port: 6789
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/nzbget/config" }
  ollama:
    port: 11434
    dirs:
      - { path: "{{ host_data_dir }}/ollama" }
  ombi:
    port: 10005
    dirs:
      - { path: "{{ host_data_dir }}/ombi/ombi_config_mount_dir" }
  open-webui:
    port: 11435
    dirs:
      - { path: "{{ host_data_dir }}/open-webui" }
  pgadmin:
    port: 3487
    dirs:
      - {
          path: "{{ host_data_dir }}/pgadmin",
          owner: "1000",
          group: "1000",
          mode: "0750",
        }
      - { path: "{{ host_data_dir }}/postgresdb", owner: "1000", group: "1000" }
  plex:
    port: 10018
    dirs:
      - {
          path: "{{ host_data_dir }}/plex/plex_config_mount_dir",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/plex/plex_transcode_mount_dir",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/plex/media_music_mount_dir",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/plex/media_movies_mount_dir",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/plex/media_tv_mount_dir",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/plex/media_courses_mount_dir",
          owner: "1000",
          group: "1000",
        }
  postiz:
    port: 5000
    dirs:
      - {
          path: "{{ host_data_dir }}/postiz/app/config",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/postiz/app/uploads",
          owner: "1000",
          group: "1000",
        }
      - { path: "{{ host_data_dir }}/postiz/db/data", owner: "1000", group: "1000" }
      - {
          path: "{{ host_data_dir }}/postiz/redis/data",
          owner: "1000",
          group: "1000",
        }
  prowlarr:
    port: 10002
    dirs:
      - { path: "{{ host_data_dir }}/prowlarr/prowlarr_config_mount_dir" }
  registry:
    port: 5000
    dirs:
      - { path: "{{ host_data_dir }}/registry" }
  sftpgo:
    port: 9393
    dirs:
      - {
          path: "{{ host_data_dir }}/sftpgo/srv/sftpgo",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/sftpgo/var/lib/sftpgo",
          owner: "1000",
          group: "1000",
        }
  sonarqube:
    port: 10026
    dirs:
      - {
          path: "{{ host_data_dir }}/sonarqube/pg_mount_dir",
          owner: "1000",
          group: "1000",
          mode: "0700",
        }
      - {
          path: "{{ host_data_dir }}/sonarqube/sonarqube_data_mount_dir",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/sonarqube/sonarqube_extensions_mount_dir",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/sonarqube/sonarqube_logs_mount_dir",
          owner: "1000",
          group: "1000",
        }
  stirling-pdf:
    port: 8086
    dirs:
      - {
          path: "{{ host_data_dir }}/stirling-pdf/configs",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/stirling-pdf/logs",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/stirling-pdf/tessdata",
          owner: "1000",
          group: "1000",
        }
      - {
          path: "{{ host_data_dir }}/stirling-pdf/pipeline",
          owner: "1000",
          group: "1000",
        }
  tautulli:
    port: 10019
    dirs:
      - { path: "{{ host_data_dir }}/tautulli/tautulli_config_mount_dir" }
  threadfin:
    port: 34400
    dirs:
      - { path: "{{ host_data_dir }}/mediaserver/threadfin/config" }
      - { path: "{{ host_data_dir }}/mediaserver/threadfin/temp" }
  upsnap:
    port: 8090
    dirs:
      - { path: "{{ host_data_dir }}/upsnap/data", owner: "1000", group: "1000" }
  wikijs:
    port: 3123
    dirs:
      - { path: "{{ host_data_dir }}/wikijs/db", mode: "0700" }
