daemon=300				# check every 300 seconds
syslog=yes				# log update msgs to syslog
pid=/var/run/ddclient/ddclient.pid		# record PID in file.
ssl=yes 				# use ssl-support.

use=web, web=dynamicdns.park-your-domain.com/getip  \
protocol=namecheap                                  \
server=dynamicdns.park-your-domain.com              \
login=wezeon.com                                    \
password=bee8b2bca9ab47e39f1e31173509613a           \
*, @
