.PHONY: start stop remove logs clean restart reset

APPS:={{ enabled_apps | join(' ') }}

start:
	for app in $(APPS) ; do \
		cd $$app ; docker compose up -d ; cd .. ; \
	done

stop:
	for app in $(APPS) ; do \
		cd ./$$app ; docker compose down ; cd .. ; \
	done

remove:
	for app in $(APPS) ; do \
		cd ./$$app ; docker compose rm ; cd .. ; \
	done

logs:
	for app in $(APPS) ; do \
		cd ./$$app ; docker compose logs ; cd .. ; \
	done

clean: stop remove

restart: stop start

reset: clean start