#!/bin/bash
set -e

psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE USER $N8N_USER PASSWORD '$N8N_PASSWORD';"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE DATABASE $N8N_DB WITH OWNER $N8N_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "REVOKE CONNECT ON DATABASE $N8N_DB FROM PUBLIC;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CONNECT ON DATABASE $N8N_DB TO $N8N_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT CREATE ON DATABASE $N8N_DB TO $N8N_USER WITH GRANT OPTION;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "ALTER ROLE $N8N_USER WITH CREATEROLE;"