#!/bin/bash
set -e

psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE USER $AIRFLOW_DB_USER PASSWORD '$AIRFLOW_DB_PASS';"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE DATABASE $AIRFLOW_DB_NAME WITH OWNER $AIRFLOW_DB_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "GRANT ALL PRIVILEGES ON DATABASE $AIRFLOW_DB_NAME TO $AIRFLOW_DB_USER;"
psql -d $POSTGRES_DB -U $POSTGRES_USER -c "ALTER ROLE $AIRFLOW_DB_USER WITH CREATEROLE;"
